language: node_js
node_js: '8'
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - npm i -g npm@
  - npm i -g greenkeeper-lockfile@1
install:
  - npm i
  - npm prune
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npx travis-deploy-once "npx semantic-release || true"
script:
  - npm run lint
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
